# Generated by Django 4.2.7 on 2024-12-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapatillasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField()),
                ('tipo_venta', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapatillasApp.producto')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapatillasApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteVentas',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('total_vendido', models.PositiveIntegerField()),
                ('fecha_reporte', models.DateTimeField()),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapatillasApp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='cod_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapatillasApp.proveedor'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_stock', models.PositiveIntegerField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cod_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zapatillasApp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_actual', models.PositiveIntegerField()),
                ('fecha_alerta', models.DateTimeField()),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapatillasApp.producto')),
            ],
        ),
    ]
