# Generated by Django 4.2.7 on 2024-12-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatillasApp', '0003_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
