# Generated by Django 4.2.7 on 2024-12-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapatillasApp', '0005_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
